package adapters

import (
	"fmt"
	"strings"
)

const (
	// AiderID identifies the Aider AI pair programming adapter.
	AiderID = "aider"

	aiderInteractionMetadata = "interaction"
	aiderApplyChanges        = "apply_changes"
	aiderRunCommand          = "run_command"
	aiderAddToChat           = "add_to_chat"
	aiderCreateFile          = "create_file"
)

type aiderPrompt struct {
	interaction string
	summary     string
	match       string
	eventType   EventType
	risk        RiskLevel
	markers     []string
	allows      []string
	denies      []string
	footers     []string
}

var aiderPrompts = []aiderPrompt{
	{
		interaction: aiderApplyChanges,
		summary:     "Aider asks to apply changes (y=allow, n=deny)",
		match:       "Apply changes?",
		eventType:   EventConfirmation,
		risk:        RiskLow,
		markers: []string{
			"Apply changes?",
			"Apply these changes?",
			"Apply change?",
			"Apply edit to",
		},
		allows:  []string{"(Y)es", "[Yes]"},
		denies:  []string{"(N)o"},
		footers: []string{"[Yes]:", "(y/n)", "(Y/n)"},
	},
	{
		interaction: aiderRunCommand,
		summary:     "Aider asks to run shell command (y=allow, n=deny)",
		match:       "Run shell command?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers: []string{
			"Run shell command?",
			"Run tests?",
			"Run command?",
		},
		allows:  []string{"(Y)es", "[Yes]"},
		denies:  []string{"(N)o"},
		footers: []string{"[Yes]:", "(y/n)", "(Y/n)"},
	},
	{
		interaction: aiderAddToChat,
		summary:     "Aider asks to add file to chat (y=allow, n=deny)",
		match:       "Add to the chat?",
		eventType:   EventPermission,
		risk:        RiskLow,
		markers: []string{
			" to the chat?",
			"Add file to the chat?",
			"Add to the chat?",
		},
		allows:  []string{"(Y)es", "[Yes]"},
		denies:  []string{"(N)o"},
		footers: []string{"[Yes]:", "(y/n)", "(Y/n)"},
	},
	{
		interaction: aiderCreateFile,
		summary:     "Aider asks to create file (y=allow, n=deny)",
		match:       "Create file?",
		eventType:   EventConfirmation,
		risk:        RiskLow,
		markers: []string{
			"Create file?",
			"Create ",
		},
		allows:  []string{"(Y)es", "[Yes]"},
		denies:  []string{"(N)o"},
		footers: []string{"[Yes]:", "(y/n)", "(Y/n)"},
	},
}

// AiderAdapter recognizes prompts generated by the Aider coding assistant CLI.
// Configured intercept_patterns retain configured priority and serve as fallback.
type AiderAdapter struct {
	generic *GenericRegexAdapter
}

// NewAiderAdapter validates and copies intercept_patterns used by generic fallback.
func NewAiderAdapter(patterns []Pattern) (*AiderAdapter, error) {
	generic, err := NewGenericRegexAdapter(patterns)
	if err != nil {
		return nil, err
	}
	return &AiderAdapter{generic: generic}, nil
}

func (*AiderAdapter) ID() string { return AiderID }

func (*AiderAdapter) snapshotFingerprintSource(normalized, active string, inCodeFence bool) string {
	prompt, found := detectAiderPrompt(normalized, active, inCodeFence)
	if !found {
		return active
	}
	if block, complete := aiderPromptBlock(normalized, active, prompt); complete {
		return prompt.interaction + "\x00" + compactFingerprintSource(block)
	}
	return active
}

func (*AiderAdapter) snapshotOccurrenceAware(event Event) bool {
	return event.Metadata[aiderInteractionMetadata] != ""
}

// Detect gives configured intercept_patterns priority. Aider prompts are
// matched only when no configured pattern matches.
func (a *AiderAdapter) Detect(state *DetectionState, chunk []byte) ([]Event, error) {
	if state == nil {
		return nil, fmt.Errorf("nil detection state")
	}
	if len(chunk) == 0 {
		return nil, nil
	}
	if state.pending != nil {
		state.appendDetectionText(chunk)
		return nil, nil
	}

	genericProbe := *state
	genericEvents, err := a.generic.Detect(&genericProbe, chunk)
	if err != nil {
		return nil, err
	}
	if len(genericEvents) > 0 {
		*state = genericProbe
		return a.rewriteGenericEvents(state, genericEvents), nil
	}

	vendorProbe := *state
	start, end, ok := vendorProbe.appendDetectionText(chunk)
	if ok {
		activeLine := vendorProbe.detectionText[start:end]
		if prompt, found := detectAiderPrompt(vendorProbe.detectionText, activeLine, vendorProbe.inCodeFence); found {
			state.appendDetectionText(chunk)
			candidate := Event{
				SessionID: state.SessionID,
				AgentID:   state.AgentID,
				Adapter:   AiderID,
				Type:      prompt.eventType,
				Summary:   prompt.summary,
				Match:     prompt.match,
				Risk:      prompt.risk,
				Metadata: map[string]string{
					aiderInteractionMetadata: prompt.interaction,
				},
			}
			candidate.Signature = stableSignature(
				state.SessionID,
				AiderID,
				prompt.eventType,
				prompt.interaction,
				prompt.match,
			)
			return []Event{state.replacePending(candidate)}, nil
		}
	}

	events, err := a.generic.Detect(state, chunk)
	if err != nil || len(events) == 0 {
		return events, err
	}
	return a.rewriteGenericEvents(state, events), nil
}

func (a *AiderAdapter) rewriteGenericEvents(state *DetectionState, events []Event) []Event {
	result := make([]Event, len(events))
	for index, event := range events {
		event.Adapter = AiderID
		event.Signature = stableSignature(
			event.SessionID,
			AiderID,
			event.Type,
			event.Summary,
			event.Match,
		)
		event.ID = occurrenceID(event.Signature, event.Sequence)
		result[index] = event
	}
	if state.pending != nil && state.pending.Adapter != AiderID {
		pending := *state.pending
		pending.Adapter = AiderID
		pending.Signature = stableSignature(
			pending.SessionID,
			AiderID,
			pending.Type,
			pending.Summary,
			pending.Match,
		)
		pending.ID = occurrenceID(pending.Signature, pending.Sequence)
		state.pending = &pending
	}
	return result
}

func detectAiderPrompt(window, activeLine string, inCodeFence bool) (aiderPrompt, bool) {
	if ignoredContext(activeLine, inCodeFence) {
		return aiderPrompt{}, false
	}
	trimmedActive := strings.TrimSpace(activeLine)
	for _, prompt := range aiderPrompts {
		footerOffset, footer := lastAiderVariant(trimmedActive, prompt.footers)
		if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
			continue
		}
		if _, complete := aiderPromptBlock(window, activeLine, prompt); complete {
			return prompt, true
		}
	}
	return aiderPrompt{}, false
}

func aiderPromptBlock(window, activeLine string, prompt aiderPrompt) (string, bool) {
	trimmedActive := strings.TrimSpace(activeLine)
	activeOffset := strings.LastIndex(window, activeLine)
	if activeOffset < 0 {
		return "", false
	}

	footerOffset, footer := lastAiderVariant(trimmedActive, prompt.footers)
	if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
		return "", false
	}

	// 1. Check if activeLine itself contains marker, allow and deny options
	allowOffset := firstAiderVariant(trimmedActive, prompt.allows)
	denyOffset := firstAiderVariant(trimmedActive, prompt.denies)
	markerOffsetInActive := firstAiderVariant(trimmedActive, prompt.markers)

	if markerOffsetInActive >= 0 && allowOffset >= 0 && denyOffset >= 0 && markerOffsetInActive <= allowOffset {
		return trimmedActive, true
	}

	// 2. Multi-line prompt: search backwards from activeLine
	footerStart := activeOffset + strings.Index(activeLine, footer)
	footerEnd := footerStart + len(footer)
	blockStart := latestAiderFooterEnd(window[:activeOffset])

	for _, marker := range prompt.markers {
		for searchEnd := footerStart; searchEnd > blockStart; {
			markerOffset := strings.LastIndex(window[blockStart:searchEnd], marker)
			if markerOffset < 0 {
				break
			}
			markerOffset += blockStart
			body := window[markerOffset:footerEnd]
			allowPos := firstAiderVariant(body, prompt.allows)
			denyPos := firstAiderVariant(body, prompt.denies)
			if allowPos >= 0 && denyPos >= 0 {
				return window[markerOffset:footerEnd], true
			}
			searchEnd = markerOffset
		}
	}
	return "", false
}

func latestAiderFooterEnd(value string) int {
	latest := 0
	for _, candidate := range aiderPrompts {
		for _, footer := range candidate.footers {
			if offset := strings.LastIndex(value, footer); offset >= 0 && offset+len(footer) > latest {
				latest = offset + len(footer)
			}
		}
	}
	return latest
}

func firstAiderVariant(value string, variants []string) int {
	first := -1
	for _, variant := range variants {
		if offset := strings.Index(value, variant); offset >= 0 && (first < 0 || offset < first) {
			first = offset
		}
	}
	return first
}

func lastAiderVariant(value string, variants []string) (int, string) {
	last := -1
	matched := ""
	for _, variant := range variants {
		if offset := strings.LastIndex(value, variant); offset > last {
			last = offset
			matched = variant
		}
	}
	return last, matched
}

// EncodeDecision encodes automated or manual responses for Aider prompts.
// Aider prompts expect Enter ('\r') to confirm input.
func (a *AiderAdapter) EncodeDecision(event Event, decision Decision, manualInput string) ([]byte, error) {
	if !event.Actionable() {
		return nil, fmt.Errorf("%w for type %q", ErrDecisionUnsupported, event.Type)
	}
	interaction := event.Metadata[aiderInteractionMetadata]
	if interaction == "" {
		return a.generic.EncodeDecision(event, decision, manualInput)
	}
	if strings.IndexByte(manualInput, 0) >= 0 {
		return nil, fmt.Errorf("invalid manual input: NUL byte")
	}
	if decision != DecisionManual && manualInput != "" {
		return nil, fmt.Errorf("an automatic Aider decision cannot carry manual input")
	}

	switch decision {
	case DecisionAllow:
		return []byte("y\r"), nil
	case DecisionDeny:
		return []byte("n\r"), nil
	case DecisionManual:
		return []byte(manualInput + "\r"), nil
	default:
		return nil, fmt.Errorf("%w: %s", ErrDecisionUnsupported, decision)
	}
}
