package adapters

import (
	"fmt"
	"slices"
	"strings"
)

const (
	// GooseID identifies the Goose AI agent adapter.
	GooseID = "goose"

	gooseInteractionMetadata = "interaction"
	gooseToolCall            = "tool_call"
	gooseToolCallWithNotice  = "tool_call_with_notice"
)

// goosePrompt is one of the menus Goose draws with cliclack's select to ask
// whether a tool call may run. The highlight starts on the first option,
// moves with j and k, stops at either end, and Enter picks the highlighted
// option; y and n do nothing, so Enter after either picks Allow.
type goosePrompt struct {
	interaction string
	summary     string
	question    string
	eventType   EventType
	risk        RiskLevel
	// options are the menu's labels, top to bottom.
	options []string
}

// goosePrompts holds the two menus Goose 1.52.0's CLI draws before a tool
// call in approve mode, observed in a PTY against a stand-in model and
// answered both ways with the side effect checked: see testdata/goose.
//
// The entries written earlier from documentation expected "(y/n)" questions
// Goose never asks, and answered them with y or n and Enter: on the real
// menu, both of those allow the call. Anything else falls back to the
// configured intercept_patterns.
var goosePrompts = []goosePrompt{
	{
		interaction: gooseToolCall,
		summary:     "Goose asks to call a tool (Allow or Deny)",
		question:    "Goose would like to call the above tool, do you allow?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		options:     []string{"Allow", "Always Allow", "Deny", "Cancel"},
	},
	// Asked instead when a check attached a notice to the call, printed above
	// the menu: extension management always carries one, and a prompt
	// injection finding does. There is no Always Allow.
	{
		interaction: gooseToolCallWithNotice,
		summary:     "Goose asks to call a tool it attached a notice to (Allow or Deny)",
		question:    "Do you allow this tool call?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		options:     []string{"Allow", "Deny", "Cancel"},
	},
}

// cliclack draws its menus with these symbols, or with the ASCII ones when
// the terminal does not take Unicode.
var (
	gooseActiveStep = []string{"◆", "*"}
	gooseBar        = []string{"│", "|"}
	gooseBarEnd     = []string{"└", "—"}
	gooseRadio      = []string{"●", "○", ">"}
)

// GooseAdapter recognizes prompts generated by the Goose CLI agent.
// Configured intercept_patterns retain configured priority and serve as fallback.
type GooseAdapter struct {
	generic *GenericRegexAdapter
}

// NewGooseAdapter validates and copies intercept_patterns used by generic fallback.
func NewGooseAdapter(patterns []Pattern) (*GooseAdapter, error) {
	generic, err := NewGenericRegexAdapter(patterns)
	if err != nil {
		return nil, err
	}
	return &GooseAdapter{generic: generic}, nil
}

func (*GooseAdapter) ID() string { return GooseID }

func (*GooseAdapter) snapshotFingerprintSource(normalized, active string, inCodeFence bool) string {
	prompt, start, _, found := gooseMenuAtEnd(normalized, inCodeFence)
	if !found {
		return active
	}
	return prompt.interaction + "\x00" + compactFingerprintSource(normalized[start:])
}

func (*GooseAdapter) snapshotOccurrenceAware(event Event) bool {
	return event.Metadata[gooseInteractionMetadata] != ""
}

// Detect gives configured intercept_patterns priority. Goose prompts are
// matched only when no configured pattern matches.
func (a *GooseAdapter) Detect(state *DetectionState, chunk []byte) ([]Event, error) {
	if state == nil {
		return nil, fmt.Errorf("nil detection state")
	}
	if len(chunk) == 0 {
		return nil, nil
	}
	if state.pending != nil {
		state.appendDetectionText(chunk)
		return nil, nil
	}

	genericProbe := *state
	genericEvents, err := a.generic.Detect(&genericProbe, chunk)
	if err != nil {
		return nil, err
	}
	if len(genericEvents) > 0 {
		*state = genericProbe
		return a.rewriteGenericEvents(state, genericEvents), nil
	}

	vendorProbe := *state
	vendorProbe.appendDetectionText(chunk)
	if prompt, start, end, found := gooseMenuAtEnd(vendorProbe.detectionText, vendorProbe.inCodeFence); found {
		questionLine := vendorProbe.detectionText[start:end]
		lineAnchor := state.anchorAt(start)
		if state.hasRendered && state.answeredOnItsRow(questionLine, lineAnchor) {
			state.appendDetectionText(chunk)
			return nil, nil
		}
		state.appendDetectionText(chunk)
		candidate := Event{
			questionLine: questionLine,
			anchor:       lineAnchor,
			SessionID:    state.SessionID,
			AgentID:      state.AgentID,
			Adapter:      GooseID,
			Type:         prompt.eventType,
			Summary:      prompt.summary,
			Match:        prompt.question,
			Risk:         prompt.risk,
			Metadata: map[string]string{
				gooseInteractionMetadata: prompt.interaction,
			},
		}
		candidate.Signature = stableSignature(
			state.SessionID,
			GooseID,
			prompt.eventType,
			prompt.interaction,
			prompt.question,
		)
		return []Event{state.replacePending(candidate)}, nil
	}

	events, err := a.generic.Detect(state, chunk)
	if err != nil || len(events) == 0 {
		return events, err
	}
	return a.rewriteGenericEvents(state, events), nil
}

func (a *GooseAdapter) rewriteGenericEvents(state *DetectionState, events []Event) []Event {
	result := make([]Event, len(events))
	for index, event := range events {
		event.Adapter = GooseID
		event.Signature = stableSignature(
			event.SessionID,
			GooseID,
			event.Type,
			event.Summary,
			event.Match,
		)
		event.ID = state.occurrenceIDFor(event.Signature, event.Sequence)
		result[index] = event
	}
	if state.pending != nil && state.pending.Adapter != GooseID {
		pending := *state.pending
		pending.Adapter = GooseID
		pending.Signature = stableSignature(
			pending.SessionID,
			GooseID,
			pending.Type,
			pending.Summary,
			pending.Match,
		)
		pending.ID = state.occurrenceIDFor(pending.Signature, pending.Sequence)
		state.pending = &pending
	}
	return result
}

// gooseMenuAtEnd finds a Goose approval menu that is the last thing in the
// window and still waits for its answer: the question after the active step
// symbol, then exactly the options of that question, then the bar's end. Once
// answered, cliclack redraws the question after the submitted symbol and
// without the options, which is not read as asked. It returns the offsets of
// the question's line in the window.
func gooseMenuAtEnd(window string, inCodeFence bool) (goosePrompt, int, int, bool) {
	end := len(strings.TrimRight(window, " \t\r\n"))
	if end == 0 || inCodeFence {
		return goosePrompt{}, 0, 0, false
	}
	lineStart := strings.LastIndexByte(window[:end], '\n') + 1
	if !gooseOneOf(strings.TrimSpace(window[lineStart:end]), gooseBarEnd) {
		return goosePrompt{}, 0, 0, false
	}
	var labels []string
	for lineEnd := lineStart - 1; lineEnd > 0; {
		start := strings.LastIndexByte(window[:lineEnd], '\n') + 1
		line := strings.TrimSpace(window[start:lineEnd])
		if label, ok := gooseOptionLabel(line); ok {
			labels = append([]string{label}, labels...)
			lineEnd = start - 1
			continue
		}
		question, ok := gooseTrimPrefix(line, gooseActiveStep)
		if !ok || ignoredContext(window[start:lineEnd], false) {
			return goosePrompt{}, 0, 0, false
		}
		for _, prompt := range goosePrompts {
			if strings.TrimSpace(question) == prompt.question && slices.Equal(labels, prompt.options) {
				return prompt, start, lineEnd, true
			}
		}
		return goosePrompt{}, 0, 0, false
	}
	return goosePrompt{}, 0, 0, false
}

// gooseOptionLabel reads "│  ● Allow (Allow the tool call once)" as "Allow".
func gooseOptionLabel(line string) (string, bool) {
	rest, ok := gooseTrimPrefix(line, gooseBar)
	if !ok {
		return "", false
	}
	rest = strings.TrimSpace(rest)
	if radio, ok := gooseTrimPrefix(rest, gooseRadio); ok {
		rest = strings.TrimSpace(radio)
	}
	if hint := strings.Index(rest, " ("); hint >= 0 {
		rest = rest[:hint]
	}
	rest = strings.TrimSpace(rest)
	return rest, rest != ""
}

func gooseTrimPrefix(value string, prefixes []string) (string, bool) {
	for _, prefix := range prefixes {
		if rest, ok := strings.CutPrefix(value, prefix); ok {
			return rest, true
		}
	}
	return "", false
}

func gooseOneOf(value string, candidates []string) bool {
	return slices.Contains(candidates, value)
}

// gooseSelect is the keys that pick the option at index whatever the
// highlight: k to the top, where it stops, j down to the option, Enter.
func gooseSelect(prompt goosePrompt, label string) ([]byte, bool) {
	index := slices.Index(prompt.options, label)
	if index < 0 {
		return nil, false
	}
	keys := strings.Repeat("k", len(prompt.options)-1) + strings.Repeat("j", index) + "\r"
	return []byte(keys), true
}

// EncodeDecision picks Allow or Deny on Goose's menu, whatever option is
// highlighted when the keys arrive. Manual input names an option: "allow",
// "deny" or "cancel"; Always Allow, which changes Goose's permissions for
// every later call, is left to the terminal.
func (a *GooseAdapter) EncodeDecision(event Event, decision Decision, manualInput string) ([]byte, error) {
	if !event.Actionable() {
		return nil, fmt.Errorf("%w for type %q", ErrDecisionUnsupported, event.Type)
	}
	interaction := event.Metadata[gooseInteractionMetadata]
	if interaction == "" {
		return a.generic.EncodeDecision(event, decision, manualInput)
	}
	if strings.IndexByte(manualInput, 0) >= 0 {
		return nil, fmt.Errorf("invalid manual input: NUL byte")
	}
	if decision != DecisionManual && manualInput != "" {
		return nil, fmt.Errorf("an automatic Goose decision cannot carry manual input")
	}
	index := slices.IndexFunc(goosePrompts, func(prompt goosePrompt) bool { return prompt.interaction == interaction })
	if index < 0 {
		return nil, fmt.Errorf("%w: Goose interaction %q", ErrDecisionUnsupported, interaction)
	}
	prompt := goosePrompts[index]

	label := ""
	switch decision {
	case DecisionAllow:
		label = "Allow"
	case DecisionDeny:
		label = "Deny"
	case DecisionManual:
		switch strings.ToLower(strings.TrimSpace(manualInput)) {
		case "allow":
			label = "Allow"
		case "deny":
			label = "Deny"
		case "cancel":
			label = "Cancel"
		}
	}
	if keys, ok := gooseSelect(prompt, label); ok {
		return keys, nil
	}
	return nil, fmt.Errorf("%w: %q for Goose interaction %q", ErrDecisionUnsupported, decision, interaction)
}
