package adapters

import (
	"fmt"
	"strings"
)

const (
	// GooseID identifies the Goose AI agent adapter.
	GooseID = "goose"

	gooseInteractionMetadata = "interaction"
	gooseExecuteTool         = "execute_tool"
	gooseRunCommand          = "run_command"
	gooseModifyFile          = "modify_file"
	gooseExtension           = "extension_approval"
)

type goosePrompt struct {
	interaction string
	summary     string
	match       string
	eventType   EventType
	risk        RiskLevel
	markers     []string
	allows      []string
	denies      []string
	footers     []string
}

var goosePrompts = []goosePrompt{
	{
		interaction: gooseExecuteTool,
		summary:     "Goose asks to execute tool (y=allow, n=deny)",
		match:       "Approve tool execution?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers: []string{
			"Approve tool execution?",
			"Allow Goose to run:",
			"Allow Goose to execute:",
			"Approve execution?",
			"Allow tool call:",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
	{
		interaction: gooseRunCommand,
		summary:     "Goose asks to run command (y=allow, n=deny)",
		match:       "Run shell command?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers: []string{
			"Run shell command?",
			"Confirm command execution?",
			"Do you want to run this command?",
			"Approve running command:",
			"Execute command?",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
	{
		interaction: gooseModifyFile,
		summary:     "Goose asks to modify file (y=allow, n=deny)",
		match:       "Approve file modification?",
		eventType:   EventConfirmation,
		risk:        RiskLow,
		markers: []string{
			"Approve file modification?",
			"Allow Goose to write:",
			"Allow Goose to edit:",
			"Confirm file changes?",
			"Modify file?",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
	{
		interaction: gooseExtension,
		summary:     "Goose asks to approve extension (y=allow, n=deny)",
		match:       "Approve extension access?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers: []string{
			"Approve extension access?",
			"Enable extension?",
			"Allow extension:",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
}

// GooseAdapter recognizes prompts generated by the Goose CLI agent.
// Configured intercept_patterns retain configured priority and serve as fallback.
type GooseAdapter struct {
	generic *GenericRegexAdapter
}

// NewGooseAdapter validates and copies intercept_patterns used by generic fallback.
func NewGooseAdapter(patterns []Pattern) (*GooseAdapter, error) {
	generic, err := NewGenericRegexAdapter(patterns)
	if err != nil {
		return nil, err
	}
	return &GooseAdapter{generic: generic}, nil
}

func (*GooseAdapter) ID() string { return GooseID }

func (*GooseAdapter) snapshotFingerprintSource(normalized, active string, inCodeFence bool) string {
	prompt, found := detectGoosePrompt(normalized, active, inCodeFence)
	if !found {
		return active
	}
	if block, complete := goosePromptBlock(normalized, active, prompt); complete {
		return prompt.interaction + "\x00" + compactFingerprintSource(block)
	}
	return active
}

func (*GooseAdapter) snapshotOccurrenceAware(event Event) bool {
	return event.Metadata[gooseInteractionMetadata] != ""
}

// Detect gives configured intercept_patterns priority. Goose prompts are
// matched only when no configured pattern matches.
func (a *GooseAdapter) Detect(state *DetectionState, chunk []byte) ([]Event, error) {
	if state == nil {
		return nil, fmt.Errorf("nil detection state")
	}
	if len(chunk) == 0 {
		return nil, nil
	}
	if state.pending != nil {
		state.appendDetectionText(chunk)
		return nil, nil
	}

	genericProbe := *state
	genericEvents, err := a.generic.Detect(&genericProbe, chunk)
	if err != nil {
		return nil, err
	}
	if len(genericEvents) > 0 {
		*state = genericProbe
		return a.rewriteGenericEvents(state, genericEvents), nil
	}

	vendorProbe := *state
	start, end, ok := vendorProbe.appendDetectionText(chunk)
	if ok {
		activeLine := vendorProbe.detectionText[start:end]
		if prompt, found := detectGoosePrompt(vendorProbe.detectionText, activeLine, vendorProbe.inCodeFence); found {
			state.appendDetectionText(chunk)
			candidate := Event{
				SessionID: state.SessionID,
				AgentID:   state.AgentID,
				Adapter:   GooseID,
				Type:      prompt.eventType,
				Summary:   prompt.summary,
				Match:     prompt.match,
				Risk:      prompt.risk,
				Metadata: map[string]string{
					gooseInteractionMetadata: prompt.interaction,
				},
			}
			if cmd := extractQuotedCommand(activeLine); cmd != "" {
				candidate.Command = cmd
			}
			candidate.Signature = stableSignature(
				state.SessionID,
				GooseID,
				prompt.eventType,
				prompt.interaction,
				prompt.match,
			)
			return []Event{state.replacePending(candidate)}, nil
		}
	}

	events, err := a.generic.Detect(state, chunk)
	if err != nil || len(events) == 0 {
		return events, err
	}
	return a.rewriteGenericEvents(state, events), nil
}

func (a *GooseAdapter) rewriteGenericEvents(state *DetectionState, events []Event) []Event {
	result := make([]Event, len(events))
	for index, event := range events {
		event.Adapter = GooseID
		event.Signature = stableSignature(
			event.SessionID,
			GooseID,
			event.Type,
			event.Summary,
			event.Match,
		)
		event.ID = occurrenceID(event.Signature, event.Sequence)
		result[index] = event
	}
	if state.pending != nil && state.pending.Adapter != GooseID {
		pending := *state.pending
		pending.Adapter = GooseID
		pending.Signature = stableSignature(
			pending.SessionID,
			GooseID,
			pending.Type,
			pending.Summary,
			pending.Match,
		)
		pending.ID = occurrenceID(pending.Signature, pending.Sequence)
		state.pending = &pending
	}
	return result
}

func detectGoosePrompt(window, activeLine string, inCodeFence bool) (goosePrompt, bool) {
	if ignoredContext(activeLine, inCodeFence) {
		return goosePrompt{}, false
	}
	trimmedActive := strings.TrimSpace(activeLine)
	for _, prompt := range goosePrompts {
		footerOffset, footer := lastGooseVariant(trimmedActive, prompt.footers)
		if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
			continue
		}
		if _, complete := goosePromptBlock(window, activeLine, prompt); complete {
			return prompt, true
		}
	}
	return goosePrompt{}, false
}

func goosePromptBlock(window, activeLine string, prompt goosePrompt) (string, bool) {
	trimmedActive := strings.TrimSpace(activeLine)
	activeOffset := strings.LastIndex(window, activeLine)
	if activeOffset < 0 {
		return "", false
	}

	footerOffset, footer := lastGooseVariant(trimmedActive, prompt.footers)
	if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
		return "", false
	}

	// 1. Check if activeLine itself contains marker, allow and deny options
	allowOffset := firstGooseVariant(trimmedActive, prompt.allows)
	denyOffset := firstGooseVariant(trimmedActive, prompt.denies)
	markerOffsetInActive := firstGooseVariant(trimmedActive, prompt.markers)

	if markerOffsetInActive >= 0 && allowOffset >= 0 && denyOffset >= 0 && markerOffsetInActive <= allowOffset {
		return trimmedActive, true
	}

	// 2. Multi-line prompt: search backwards from activeLine
	footerStart := activeOffset + strings.Index(activeLine, footer)
	footerEnd := footerStart + len(footer)
	blockStart := latestGooseFooterEnd(window[:activeOffset])

	for _, marker := range prompt.markers {
		for searchEnd := footerStart; searchEnd > blockStart; {
			markerOffset := strings.LastIndex(window[blockStart:searchEnd], marker)
			if markerOffset < 0 {
				break
			}
			markerOffset += blockStart
			body := window[markerOffset:footerEnd]
			allowPos := firstGooseVariant(body, prompt.allows)
			denyPos := firstGooseVariant(body, prompt.denies)
			if allowPos >= 0 && denyPos >= 0 {
				return window[markerOffset:footerEnd], true
			}
			searchEnd = markerOffset
		}
	}
	return "", false
}

func latestGooseFooterEnd(value string) int {
	latest := 0
	for _, candidate := range goosePrompts {
		for _, footer := range candidate.footers {
			if offset := strings.LastIndex(value, footer); offset >= 0 && offset+len(footer) > latest {
				latest = offset + len(footer)
			}
		}
	}
	return latest
}

func firstGooseVariant(value string, variants []string) int {
	first := -1
	for _, variant := range variants {
		if offset := strings.Index(value, variant); offset >= 0 && (first < 0 || offset < first) {
			first = offset
		}
	}
	return first
}

func lastGooseVariant(value string, variants []string) (int, string) {
	last := -1
	matched := ""
	for _, variant := range variants {
		if offset := strings.LastIndex(value, variant); offset > last {
			last = offset
			matched = variant
		}
	}
	return last, matched
}

// EncodeDecision encodes automated or manual responses for Goose prompts.
// Goose prompts expect Enter ('\r') to confirm input.
func (a *GooseAdapter) EncodeDecision(event Event, decision Decision, manualInput string) ([]byte, error) {
	if !event.Actionable() {
		return nil, fmt.Errorf("%w for type %q", ErrDecisionUnsupported, event.Type)
	}
	interaction := event.Metadata[gooseInteractionMetadata]
	if interaction == "" {
		return a.generic.EncodeDecision(event, decision, manualInput)
	}
	if strings.IndexByte(manualInput, 0) >= 0 {
		return nil, fmt.Errorf("invalid manual input: NUL byte")
	}
	if decision != DecisionManual && manualInput != "" {
		return nil, fmt.Errorf("an automatic Goose decision cannot carry manual input")
	}

	switch decision {
	case DecisionAllow:
		return []byte("y\r"), nil
	case DecisionDeny:
		return []byte("n\r"), nil
	case DecisionManual:
		return []byte(manualInput + "\r"), nil
	default:
		return nil, fmt.Errorf("%w: %s", ErrDecisionUnsupported, decision)
	}
}
