package adapters

import (
	"fmt"
	"strings"
)

const (
	// OpenInterpreterID identifies the Open Interpreter AI agent adapter.
	OpenInterpreterID = "interpreter"

	openinterpreterInteractionMetadata = "interaction"
	openinterpreterRunCode             = "run_code"
	openinterpreterRunCommand          = "run_command"
	openinterpreterInstallPackage      = "install_package"
	openinterpreterSaveFile            = "save_file"
)

type openinterpreterPrompt struct {
	interaction string
	summary     string
	match       string
	eventType   EventType
	risk        RiskLevel
	markers     []string
	allows      []string
	denies      []string
	footers     []string
}

var openinterpreterPrompts = []openinterpreterPrompt{
	{
		interaction: openinterpreterRunCode,
		summary:     "Open Interpreter asks to run code (y=allow, n=deny)",
		match:       "Would you like to run this code?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers: []string{
			"Would you like to run this code?",
			"Would you like to run the following code?",
			"Execute this code?",
			"Execute this Python code?",
			"Execute this bash code?",
			"Execute this shell code?",
			"Run this code?",
			"Run the following code?",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
	{
		interaction: openinterpreterRunCommand,
		summary:     "Open Interpreter asks to run shell command (y=allow, n=deny)",
		match:       "Would you like to run this command?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers: []string{
			"Would you like to run this command?",
			"Would you like to run the following command?",
			"Execute this command?",
			"Execute this shell command?",
			"Run shell command?",
			"Run this command?",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
	{
		interaction: openinterpreterInstallPackage,
		summary:     "Open Interpreter asks to install package (y=allow, n=deny)",
		match:       "Would you like to install this package?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers: []string{
			"Would you like to install this package?",
			"Install this package?",
			"Install dependencies?",
			"Install the following package?",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
	{
		interaction: openinterpreterSaveFile,
		summary:     "Open Interpreter asks to save file changes (y=allow, n=deny)",
		match:       "Would you like to save these changes?",
		eventType:   EventConfirmation,
		risk:        RiskLow,
		markers: []string{
			"Would you like to save these changes?",
			"Save these changes?",
			"Save changes?",
			"Save this file?",
		},
		allows:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y)es", "[y]es", "(Y)es", "[Yes]"},
		denies:  []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(n)o", "[n]o", "(N)o", "[No]"},
		footers: []string{"(y/n)", "(Y/n)", "[y/n]", "[Y/n]", "(y/n):", "[y/n]:", "(y/N)", "[y/N]"},
	},
}

// OpenInterpreterAdapter recognizes prompts generated by the Open Interpreter CLI.
// Configured intercept_patterns retain configured priority and serve as fallback.
type OpenInterpreterAdapter struct {
	generic *GenericRegexAdapter
}

// NewOpenInterpreterAdapter validates and copies intercept_patterns used by generic fallback.
func NewOpenInterpreterAdapter(patterns []Pattern) (*OpenInterpreterAdapter, error) {
	generic, err := NewGenericRegexAdapter(patterns)
	if err != nil {
		return nil, err
	}
	return &OpenInterpreterAdapter{generic: generic}, nil
}

func (*OpenInterpreterAdapter) ID() string { return OpenInterpreterID }

func (*OpenInterpreterAdapter) snapshotFingerprintSource(normalized, active string, inCodeFence bool) string {
	prompt, found := detectOpenInterpreterPrompt(normalized, active, inCodeFence)
	if !found {
		return active
	}
	if block, complete := openinterpreterPromptBlock(normalized, active, prompt); complete {
		return prompt.interaction + "\x00" + compactFingerprintSource(block)
	}
	return active
}

func (*OpenInterpreterAdapter) snapshotOccurrenceAware(event Event) bool {
	return event.Metadata[openinterpreterInteractionMetadata] != ""
}

// Detect gives configured intercept_patterns priority. Open Interpreter prompts are
// matched only when no configured pattern matches.
func (a *OpenInterpreterAdapter) Detect(state *DetectionState, chunk []byte) ([]Event, error) {
	if state == nil {
		return nil, fmt.Errorf("nil detection state")
	}
	if len(chunk) == 0 {
		return nil, nil
	}
	if state.pending != nil {
		state.appendDetectionText(chunk)
		return nil, nil
	}

	genericProbe := *state
	genericEvents, err := a.generic.Detect(&genericProbe, chunk)
	if err != nil {
		return nil, err
	}
	if len(genericEvents) > 0 {
		*state = genericProbe
		return a.rewriteGenericEvents(state, genericEvents), nil
	}

	vendorProbe := *state
	start, end, ok := vendorProbe.appendDetectionText(chunk)
	if ok {
		activeLine := vendorProbe.detectionText[start:end]
		if prompt, found := detectOpenInterpreterPrompt(vendorProbe.detectionText, activeLine, vendorProbe.inCodeFence); found {
			state.appendDetectionText(chunk)
			candidate := Event{
				SessionID: state.SessionID,
				AgentID:   state.AgentID,
				Adapter:   OpenInterpreterID,
				Type:      prompt.eventType,
				Summary:   prompt.summary,
				Match:     prompt.match,
				Risk:      prompt.risk,
				Metadata: map[string]string{
					openinterpreterInteractionMetadata: prompt.interaction,
				},
			}
			if cmd := extractQuotedCommand(activeLine); cmd != "" {
				candidate.Command = cmd
			}
			candidate.Signature = stableSignature(
				state.SessionID,
				OpenInterpreterID,
				prompt.eventType,
				prompt.interaction,
				prompt.match,
			)
			return []Event{state.replacePending(candidate)}, nil
		}
	}

	events, err := a.generic.Detect(state, chunk)
	if err != nil || len(events) == 0 {
		return events, err
	}
	return a.rewriteGenericEvents(state, events), nil
}

func (a *OpenInterpreterAdapter) rewriteGenericEvents(state *DetectionState, events []Event) []Event {
	result := make([]Event, len(events))
	for index, event := range events {
		event.Adapter = OpenInterpreterID
		event.Signature = stableSignature(
			event.SessionID,
			OpenInterpreterID,
			event.Type,
			event.Summary,
			event.Match,
		)
		event.ID = occurrenceID(event.Signature, event.Sequence)
		result[index] = event
	}
	if state.pending != nil && state.pending.Adapter != OpenInterpreterID {
		pending := *state.pending
		pending.Adapter = OpenInterpreterID
		pending.Signature = stableSignature(
			pending.SessionID,
			OpenInterpreterID,
			pending.Type,
			pending.Summary,
			pending.Match,
		)
		pending.ID = occurrenceID(pending.Signature, pending.Sequence)
		state.pending = &pending
	}
	return result
}

func detectOpenInterpreterPrompt(window, activeLine string, inCodeFence bool) (openinterpreterPrompt, bool) {
	if ignoredContext(activeLine, inCodeFence) {
		return openinterpreterPrompt{}, false
	}
	trimmedActive := strings.TrimSpace(activeLine)
	for _, prompt := range openinterpreterPrompts {
		footerOffset, footer := lastOpenInterpreterVariant(trimmedActive, prompt.footers)
		if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
			continue
		}
		if _, complete := openinterpreterPromptBlock(window, activeLine, prompt); complete {
			return prompt, true
		}
	}
	return openinterpreterPrompt{}, false
}

func openinterpreterPromptBlock(window, activeLine string, prompt openinterpreterPrompt) (string, bool) {
	trimmedActive := strings.TrimSpace(activeLine)
	activeOffset := strings.LastIndex(window, activeLine)
	if activeOffset < 0 {
		return "", false
	}

	footerOffset, footer := lastOpenInterpreterVariant(trimmedActive, prompt.footers)
	if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
		return "", false
	}

	// 1. Check if activeLine itself contains marker, allow and deny options
	allowOffset := firstOpenInterpreterVariant(trimmedActive, prompt.allows)
	denyOffset := firstOpenInterpreterVariant(trimmedActive, prompt.denies)
	markerOffsetInActive := firstOpenInterpreterVariant(trimmedActive, prompt.markers)

	if markerOffsetInActive >= 0 && allowOffset >= 0 && denyOffset >= 0 && markerOffsetInActive <= allowOffset {
		return trimmedActive, true
	}

	// 2. Multi-line prompt: search backwards from activeLine
	footerStart := activeOffset + strings.Index(activeLine, footer)
	footerEnd := footerStart + len(footer)
	blockStart := latestOpenInterpreterFooterEnd(window[:activeOffset])

	for _, marker := range prompt.markers {
		for searchEnd := footerStart; searchEnd > blockStart; {
			markerOffset := strings.LastIndex(window[blockStart:searchEnd], marker)
			if markerOffset < 0 {
				break
			}
			markerOffset += blockStart
			body := window[markerOffset:footerEnd]
			allowPos := firstOpenInterpreterVariant(body, prompt.allows)
			denyPos := firstOpenInterpreterVariant(body, prompt.denies)
			if allowPos >= 0 && denyPos >= 0 {
				return window[markerOffset:footerEnd], true
			}
			searchEnd = markerOffset
		}
	}
	return "", false
}

func latestOpenInterpreterFooterEnd(value string) int {
	latest := 0
	for _, candidate := range openinterpreterPrompts {
		for _, footer := range candidate.footers {
			if offset := strings.LastIndex(value, footer); offset >= 0 && offset+len(footer) > latest {
				latest = offset + len(footer)
			}
		}
	}
	return latest
}

func firstOpenInterpreterVariant(value string, variants []string) int {
	first := -1
	for _, variant := range variants {
		if offset := strings.Index(value, variant); offset >= 0 && (first < 0 || offset < first) {
			first = offset
		}
	}
	return first
}

func lastOpenInterpreterVariant(value string, variants []string) (int, string) {
	last := -1
	matched := ""
	for _, variant := range variants {
		if offset := strings.LastIndex(value, variant); offset > last {
			last = offset
			matched = variant
		}
	}
	return last, matched
}

// EncodeDecision encodes automated or manual responses for Open Interpreter prompts.
// Open Interpreter prompts expect Enter ('\r') to confirm input.
func (a *OpenInterpreterAdapter) EncodeDecision(event Event, decision Decision, manualInput string) ([]byte, error) {
	if !event.Actionable() {
		return nil, fmt.Errorf("%w for type %q", ErrDecisionUnsupported, event.Type)
	}
	interaction := event.Metadata[openinterpreterInteractionMetadata]
	if interaction == "" {
		return a.generic.EncodeDecision(event, decision, manualInput)
	}
	if strings.IndexByte(manualInput, 0) >= 0 {
		return nil, fmt.Errorf("invalid manual input: NUL byte")
	}
	if decision != DecisionManual && manualInput != "" {
		return nil, fmt.Errorf("an automatic Open Interpreter decision cannot carry manual input")
	}

	switch decision {
	case DecisionAllow:
		return []byte("y\r"), nil
	case DecisionDeny:
		return []byte("n\r"), nil
	case DecisionManual:
		return []byte(manualInput + "\r"), nil
	default:
		return nil, fmt.Errorf("%w: %s", ErrDecisionUnsupported, decision)
	}
}
