package adapters

import (
	"fmt"
	"strings"
)

const (
	// OpenInterpreterID identifies the Open Interpreter AI agent adapter.
	OpenInterpreterID = "interpreter"

	openinterpreterInteractionMetadata = "interaction"
	openinterpreterRunCode             = "run_code"
	openinterpreterScanCode            = "scan_code"
)

type openinterpreterPrompt struct {
	interaction string
	summary     string
	match       string
	eventType   EventType
	risk        RiskLevel
	markers     []string
	allows      []string
	denies      []string
	footers     []string
}

// openinterpreterPrompts holds the two questions Open Interpreter 0.4.3's
// terminal interface asks before it runs code, observed in a PTY against a
// stand-in model and answered both ways with the side effect checked: see
// testdata/interpreter. The options are "(y/n)" alone, on the question's
// line, and the answer is read as a line on the next.
//
// The entries written earlier from documentation, for installing a package,
// saving a file or running a command, named questions this version never
// asks; they are gone, and anything like them falls back to the configured
// intercept_patterns.
var openinterpreterPrompts = []openinterpreterPrompt{
	{
		interaction: openinterpreterRunCode,
		summary:     "Open Interpreter asks to run code (y=allow, n=deny)",
		match:       "Would you like to run this code?",
		eventType:   EventPermission,
		risk:        RiskHigh,
		markers:     []string{"Would you like to run this code?"},
		allows:      []string{"(y/n)"},
		denies:      []string{"(y/n)"},
		footers:     []string{"(y/n)"},
	},
	// Asked first in --safe_mode ask: y runs semgrep over the code, n skips
	// the scan, and the run question follows either way.
	{
		interaction: openinterpreterScanCode,
		summary:     "Open Interpreter asks to scan code before running it (y=allow, n=deny)",
		match:       "Would you like to scan this code?",
		eventType:   EventConfirmation,
		risk:        RiskLow,
		markers:     []string{"Would you like to scan this code?"},
		allows:      []string{"(y/n)"},
		denies:      []string{"(y/n)"},
		footers:     []string{"(y/n)"},
	},
}

// OpenInterpreterAdapter recognizes prompts generated by the Open Interpreter CLI.
// Configured intercept_patterns retain configured priority and serve as fallback.
type OpenInterpreterAdapter struct {
	generic *GenericRegexAdapter
}

// NewOpenInterpreterAdapter validates and copies intercept_patterns used by generic fallback.
func NewOpenInterpreterAdapter(patterns []Pattern) (*OpenInterpreterAdapter, error) {
	generic, err := NewGenericRegexAdapter(patterns)
	if err != nil {
		return nil, err
	}
	return &OpenInterpreterAdapter{generic: generic}, nil
}

func (*OpenInterpreterAdapter) ID() string { return OpenInterpreterID }

func (*OpenInterpreterAdapter) snapshotFingerprintSource(normalized, active string, inCodeFence bool) string {
	prompt, found := detectOpenInterpreterPrompt(normalized, active, inCodeFence)
	if !found {
		return active
	}
	if block, complete := openinterpreterPromptBlock(normalized, active, prompt); complete {
		return prompt.interaction + "\x00" + compactFingerprintSource(block)
	}
	return active
}

func (*OpenInterpreterAdapter) snapshotOccurrenceAware(event Event) bool {
	return event.Metadata[openinterpreterInteractionMetadata] != ""
}

// Detect gives configured intercept_patterns priority. Open Interpreter prompts are
// matched only when no configured pattern matches.
func (a *OpenInterpreterAdapter) Detect(state *DetectionState, chunk []byte) ([]Event, error) {
	if state == nil {
		return nil, fmt.Errorf("nil detection state")
	}
	if len(chunk) == 0 {
		return nil, nil
	}
	if state.pending != nil {
		state.appendDetectionText(chunk)
		return nil, nil
	}

	genericProbe := *state
	genericEvents, err := a.generic.Detect(&genericProbe, chunk)
	if err != nil {
		return nil, err
	}
	if len(genericEvents) > 0 {
		*state = genericProbe
		return a.rewriteGenericEvents(state, genericEvents), nil
	}

	vendorProbe := *state
	start, end, ok := vendorProbe.appendDetectionText(chunk)
	if !ok {
		start, end, ok = openinterpreterQuestionAboveAnswer(vendorProbe.detectionText)
	}
	if ok {
		activeLine := vendorProbe.detectionText[start:end]
		if prompt, found := detectOpenInterpreterPrompt(vendorProbe.detectionText, activeLine, vendorProbe.inCodeFence); found {
			lineAnchor := state.anchorAt(start)
			// The footer is found anywhere on the line, so the answer echoed
			// after "(y/n)" still matches, and on a rendered screen the
			// answered question stays painted. Only the memory of it, on its
			// row, keeps the next write from asking it again. On its row only:
			// the same question drawn elsewhere after a clear is asked again,
			// see answeredOnItsRow.
			if state.hasRendered && state.answeredOnItsRow(activeLine, lineAnchor) {
				state.appendDetectionText(chunk)
				return nil, nil
			}
			state.appendDetectionText(chunk)
			candidate := Event{
				questionLine: activeLine,
				anchor:       lineAnchor,
				SessionID:    state.SessionID,
				AgentID:      state.AgentID,
				Adapter:      OpenInterpreterID,
				Type:         prompt.eventType,
				Summary:      prompt.summary,
				Match:        prompt.match,
				Risk:         prompt.risk,
				Metadata: map[string]string{
					openinterpreterInteractionMetadata: prompt.interaction,
				},
			}
			if cmd := extractQuotedCommand(activeLine); cmd != "" {
				candidate.Command = cmd
			}
			candidate.Signature = stableSignature(
				state.SessionID,
				OpenInterpreterID,
				prompt.eventType,
				prompt.interaction,
				prompt.match,
			)
			return []Event{state.replacePending(candidate)}, nil
		}
	}

	events, err := a.generic.Detect(state, chunk)
	if err != nil || len(events) == 0 {
		return events, err
	}
	return a.rewriteGenericEvents(state, events), nil
}

func (a *OpenInterpreterAdapter) rewriteGenericEvents(state *DetectionState, events []Event) []Event {
	result := make([]Event, len(events))
	for index, event := range events {
		event.Adapter = OpenInterpreterID
		event.Signature = stableSignature(
			event.SessionID,
			OpenInterpreterID,
			event.Type,
			event.Summary,
			event.Match,
		)
		event.ID = state.occurrenceIDFor(event.Signature, event.Sequence)
		result[index] = event
	}
	if state.pending != nil && state.pending.Adapter != OpenInterpreterID {
		pending := *state.pending
		pending.Adapter = OpenInterpreterID
		pending.Signature = stableSignature(
			pending.SessionID,
			OpenInterpreterID,
			pending.Type,
			pending.Summary,
			pending.Match,
		)
		pending.ID = state.occurrenceIDFor(pending.Signature, pending.Sequence)
		state.pending = &pending
	}
	return result
}

// openinterpreterQuestionAboveAnswer finds the question line when the active
// line is the blank one Open Interpreter reads the answer on. It prints the
// question, then "\n\n  ", and waits: written in one piece, as it is unless a
// repaint came first, the question is two lines above a line holding only the
// indentation. Only blank lines may follow the question, no more than two
// line breaks' worth, so a question with anything printed after it is not
// read here.
func openinterpreterQuestionAboveAnswer(text string) (start, end int, ok bool) {
	end = len(strings.TrimRight(text, " \t\r\n"))
	if end == 0 || strings.Count(text[end:], "\n") > 2 {
		return 0, 0, false
	}
	start = strings.LastIndexByte(text[:end], '\n') + 1
	return start, end, true
}

func detectOpenInterpreterPrompt(window, activeLine string, inCodeFence bool) (openinterpreterPrompt, bool) {
	if ignoredContext(activeLine, inCodeFence) {
		return openinterpreterPrompt{}, false
	}
	trimmedActive := strings.TrimSpace(activeLine)
	for _, prompt := range openinterpreterPrompts {
		footerOffset, footer := lastOpenInterpreterVariant(trimmedActive, prompt.footers)
		if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
			continue
		}
		if _, complete := openinterpreterPromptBlock(window, activeLine, prompt); complete {
			return prompt, true
		}
	}
	return openinterpreterPrompt{}, false
}

func openinterpreterPromptBlock(window, activeLine string, prompt openinterpreterPrompt) (string, bool) {
	trimmedActive := strings.TrimSpace(activeLine)
	activeOffset := strings.LastIndex(window, activeLine)
	if activeOffset < 0 {
		return "", false
	}

	footerOffset, footer := lastOpenInterpreterVariant(trimmedActive, prompt.footers)
	if footerOffset < 0 || quotedMatch(trimmedActive, footerOffset, footerOffset+len(footer)) {
		return "", false
	}

	// 1. Check if activeLine itself contains marker, allow and deny options
	allowOffset := firstOpenInterpreterVariant(trimmedActive, prompt.allows)
	denyOffset := firstOpenInterpreterVariant(trimmedActive, prompt.denies)
	markerOffsetInActive := firstOpenInterpreterVariant(trimmedActive, prompt.markers)

	if markerOffsetInActive >= 0 && allowOffset >= 0 && denyOffset >= 0 && markerOffsetInActive <= allowOffset {
		return trimmedActive, true
	}

	// 2. Multi-line prompt: search backwards from activeLine
	footerStart := activeOffset + strings.Index(activeLine, footer)
	footerEnd := footerStart + len(footer)
	blockStart := latestOpenInterpreterFooterEnd(window[:activeOffset])

	for _, marker := range prompt.markers {
		for searchEnd := footerStart; searchEnd > blockStart; {
			markerOffset := strings.LastIndex(window[blockStart:searchEnd], marker)
			if markerOffset < 0 {
				break
			}
			markerOffset += blockStart
			body := window[markerOffset:footerEnd]
			allowPos := firstOpenInterpreterVariant(body, prompt.allows)
			denyPos := firstOpenInterpreterVariant(body, prompt.denies)
			if allowPos >= 0 && denyPos >= 0 {
				return window[markerOffset:footerEnd], true
			}
			searchEnd = markerOffset
		}
	}
	return "", false
}

func latestOpenInterpreterFooterEnd(value string) int {
	latest := 0
	for _, candidate := range openinterpreterPrompts {
		for _, footer := range candidate.footers {
			if offset := strings.LastIndex(value, footer); offset >= 0 && offset+len(footer) > latest {
				latest = offset + len(footer)
			}
		}
	}
	return latest
}

func firstOpenInterpreterVariant(value string, variants []string) int {
	first := -1
	for _, variant := range variants {
		if offset := strings.Index(value, variant); offset >= 0 && (first < 0 || offset < first) {
			first = offset
		}
	}
	return first
}

func lastOpenInterpreterVariant(value string, variants []string) (int, string) {
	last := -1
	matched := ""
	for _, variant := range variants {
		if offset := strings.LastIndex(value, variant); offset > last {
			last = offset
			matched = variant
		}
	}
	return last, matched
}

// EncodeDecision encodes automated or manual responses for Open Interpreter prompts.
// Open Interpreter prompts expect Enter ('\r') to confirm input.
func (a *OpenInterpreterAdapter) EncodeDecision(event Event, decision Decision, manualInput string) ([]byte, error) {
	if !event.Actionable() {
		return nil, fmt.Errorf("%w for type %q", ErrDecisionUnsupported, event.Type)
	}
	interaction := event.Metadata[openinterpreterInteractionMetadata]
	if interaction == "" {
		return a.generic.EncodeDecision(event, decision, manualInput)
	}
	if strings.IndexByte(manualInput, 0) >= 0 {
		return nil, fmt.Errorf("invalid manual input: NUL byte")
	}
	if decision != DecisionManual && manualInput != "" {
		return nil, fmt.Errorf("an automatic Open Interpreter decision cannot carry manual input")
	}

	switch decision {
	case DecisionAllow:
		return []byte("y\r"), nil
	case DecisionDeny:
		return []byte("n\r"), nil
	case DecisionManual:
		return []byte(manualInput + "\r"), nil
	default:
		return nil, fmt.Errorf("%w: %s", ErrDecisionUnsupported, decision)
	}
}
